spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  jwt:
    signing-secret: ${JWT_SIGNING_SECRET}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  demo:
    enabled: false
  storage:
    endpoint: ${STORAGE_ENDPOINT}
    public-endpoint: ${STORAGE_PUBLIC_ENDPOINT}
    access-key: ${STORAGE_ACCESS_KEY}
    secret-key: ${STORAGE_SECRET_KEY}
    bucket: ${STORAGE_BUCKET}
