spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/work_training_system}
    username: ${DB_USERNAME:work_training_system}
    password: ${DB_PASSWORD:work_training_system}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  flyway:
    enabled: true
