import { FormEvent, useState } from 'react'
import { api, apiBaseUrl, authStore, login, Role, Session } from './api'

type IconName = 'grid' | 'book' | 'badge' | 'certificate' | 'qr' | 'bell' | 'chart' | 'audit' | 'users' | 'settings' | 'logout' | 'arrow' | 'play' | 'check' | 'menu' | 'close'
function Icon({ name, size = 18 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, string> = { grid: 'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z', book: 'M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5zM4 5.5v16', badge: 'M12 3l2.5 5.1 5.5.8-4 4 .9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-4 5.5-.8z', certificate: 'M6 3h12v18l-6-3-6 3z', qr: 'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h2v2h-2zM18 14h2v6h-2zM14 18h4', bell: 'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4', chart: 'M4 19V5M4 19h17M8 16v-4M12 16V8M16 16v-7M20 16v-4', audit: 'M6 3h12v18H6zM9 7h6M9 11h6M9 15h4', users: 'M16 20v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2M9.5 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM20 20v-2a4 4 0 0 0-3-3.9M16 2.1a4 4 0 0 1 0 7.8', settings: 'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.7 1.7-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.1h-2.4v-.1a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L8 17l.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.6-1H6v-2.4h.1a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L7.3 8 9 6.3l.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6V5h2.4v.1a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.1 8l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.1v2.4h-.1a1.7 1.7 0 0 0-.9 1.6z', logout: 'M10 17l5-5-5-5M15 12H3M21 19V5a2 2 0 0 0-2-2h-6', arrow: 'M5 12h14M13 6l6 6-6 6', play: 'M8 5v14l11-7z', check: 'M5 12l4 4L19 6', menu: 'M4 6h16M4 12h16M4 18h16', close: 'M6 6l12 12M18 6L6 18' }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]} /></svg>
}

const demo: Session = { accessToken: 'demo', refreshToken: 'demo', user: { id: 'demo', email: 'marina@northstar.com', role: 'MANAGER' } }
const nav = [{ label: 'Overview', icon: 'grid' as IconName }, { label: 'Assignments', icon: 'book' as IconName }, { label: 'Qualifications', icon: 'badge' as IconName }, { label: 'Certificates', icon: 'certificate' as IconName }, { label: 'QR verification', icon: 'qr' as IconName }, { label: 'Notifications', icon: 'bell' as IconName }]
const management = [{ label: 'Team insights', icon: 'users' as IconName }, { label: 'Reports', icon: 'chart' as IconName }, { label: 'Audit trail', icon: 'audit' as IconName }]
function initials(email: string) { return email.split('@')[0].slice(0, 2).toUpperCase() }

export function App() {
  const [session, setSession] = useState<Session | null>(authStore.get())
  if (!session) return <Login onLogin={setSession} />
  return <Shell session={session} onLogout={() => { authStore.clear(); setSession(null) }} />
}

function Login({ onLogin }: { onLogin: (s: Session) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { onLogin(await login(email, password)) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to sign in.'); } finally { setBusy(false) } }
  return <main className="login-page"><section className="login-art"><div className="brand"><span className="brand-mark">N</span><span>northstar<span className="brand-dot">.</span></span></div><div className="art-copy"><p className="eyebrow">LEARNING OPERATIONS</p><h1>Build confidence<br />into every shift.</h1><p>A calm, clear place for teams to learn, qualify and perform at their best.</p></div><div className="art-note"><span>✦</span> Designed for the people doing the work.</div></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit}><div className="mobile-brand brand"><span className="brand-mark">N</span><span>northstar<span className="brand-dot">.</span></span></div><p className="eyebrow">WELCOME BACK</p><h2>Sign in to your workspace</h2><p className="muted">Use your work email to continue.</p><label>Email address<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@company.com" /></label><label>Password<div className="password-field"><input type="password" required value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter your password" /><span>Show</span></div></label>{error && <p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'} {!busy && <Icon name="arrow" size={16} />}</button><button type="button" className="demo-link" onClick={() => { authStore.set(demo); onLogin(demo) }}>Explore demo workspace</button><p className="api-hint">API: {apiBaseUrl}</p></form></section></main>
}

function Shell({ session, onLogout }: { session: Session; onLogout: () => void }) {
  const [active, setActive] = useState('Overview'); const [open, setOpen] = useState(false)
  const isEmployee = session.user.role === 'EMPLOYEE'; const items = isEmployee ? nav.slice(0, 5) : nav.concat(management)
  return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="side-brand brand"><span className="brand-mark">N</span><span>northstar<span className="brand-dot">.</span></span><button className="icon-button side-close" onClick={() => setOpen(false)} aria-label="Close navigation"><Icon name="close" /></button></div><div className="workspace-switcher"><span className="workspace-icon">A</span><span><strong>Atlas Manufacturing</strong><small>Operations workspace</small></span><span className="chevron">⌄</span></div><nav aria-label="Main navigation"><p className="nav-heading">WORKSPACE</p>{items.slice(0, 5).map(item => <NavItem key={item.label} item={item} active={active} setActive={setActive} />)}{!isEmployee && <><p className="nav-heading space-top">MANAGE</p>{management.map(item => <NavItem key={item.label} item={item} active={active} setActive={setActive} />)}</>}</nav><div className="sidebar-bottom"><button className="nav-item"><Icon name="settings" /> Settings</button><button className="nav-item" onClick={onLogout}><Icon name="logout" /> Sign out</button></div></aside><div className="main"><header className="topbar"><button className="icon-button menu-button" onClick={() => setOpen(true)} aria-label="Open navigation"><Icon name="menu" /></button><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>{active}</strong></div><div className="top-actions"><button className="icon-button notification" aria-label="Notifications"><Icon name="bell" /><i /></button><div className="avatar">{initials(session.user.email)}</div><div className="profile"><strong>{session.user.email.split('@')[0]}</strong><small>{session.user.role.toLowerCase()}</small></div><span className="chevron">⌄</span></div></header><main className="content"><Dashboard active={active} session={session} /></main></div></div>
}
function NavItem({ item, active, setActive }: { item: { label: string; icon: IconName }; active: string; setActive: (x: string) => void }) { return <button className={active === item.label ? 'nav-item active' : 'nav-item'} onClick={() => setActive(item.label)}><Icon name={item.icon} /> {item.label}{item.label === 'Assignments' && <span className="nav-count">3</span>}</button> }

function Dashboard({ active, session }: { active: string; session: Session }) {
  const employee = session.user.role === 'EMPLOYEE';
  if (active !== 'Overview') return <Placeholder title={active} employee={employee} />
  return <><div className="page-heading"><div><p className="eyebrow">{employee ? 'YOUR LEARNING PLAN' : 'MONDAY, JULY 25, 2026'}</p><h1>{employee ? 'Keep your momentum, Marina.' : 'Good morning, Marina.'}</h1><p className="muted">{employee ? 'Small steps today make every shift safer tomorrow.' : 'Here is the pulse of your learning operation.'}</p></div><button className="outline"><span>Last 30 days</span>⌄</button></div><section className="hero-card"><div><span className="status-pill"><i /> ON TRACK</span><h2>{employee ? 'Continue your learning' : 'Your team is building momentum'}</h2><p>{employee ? 'You are 45% through your assigned safety pathway.' : '78% of active assignments are progressing or complete.'}</p><button className="light-button">{employee ? 'Resume training' : 'View team progress'} <Icon name="arrow" size={16} /></button></div><div className="hero-orbit"><div className="orbit-center">78<small>%</small></div><svg viewBox="0 0 180 180"><circle cx="90" cy="90" r="72" /><circle className="progress-ring" cx="90" cy="90" r="72" /></svg></div></section><div className="section-title"><h2>At a glance</h2><button className="text-button">View detailed report <Icon name="arrow" size={15} /></button></div><div className="stats-grid"><Stat label="Active learners" value="126" trend="+12%" detail="vs. last month" icon="users" color="blue" /><Stat label="Completed" value="842" trend="+8.4%" detail="this month" icon="check" color="mint" /><Stat label="Needs attention" value="18" trend="-4.2%" detail="vs. last month" icon="bell" color="amber" /></div><div className="lower-grid"><section className="panel assignments"><div className="panel-heading"><div><h2>Recent assignments</h2><p className="muted">The latest learning activity across your team.</p></div><button className="icon-button"><Icon name="arrow" /></button></div><Assignment name="Confined Spaces Safety" person="J. Williams" progress={82} status="In progress" tone="blue" /><Assignment name="Forklift Operations · Refresher" person="S. Patel" progress={100} status="Completed" tone="green" /><Assignment name="Lockout / Tagout Procedures" person="R. Chen" progress={25} status="Needs attention" tone="amber" /></section><section className="panel deadlines"><div className="panel-heading"><div><h2>Upcoming deadlines</h2><p className="muted">Stay ahead of what is next.</p></div></div><Deadline date="28" month="JUL" title="Annual safety refresher" meta="12 learners · 3 days" /><Deadline date="02" month="AUG" title="Forklift certification" meta="4 learners · 8 days" /><Deadline date="14" month="AUG" title="Emergency response" meta="18 learners · 20 days" /></section></div></>
}
function Stat({ label, value, trend, detail, icon, color }: { label: string; value: string; trend: string; detail: string; icon: IconName; color: string }) { return <div className="stat-card"><div className={`stat-icon ${color}`}><Icon name={icon} size={17} /></div><p>{label}</p><strong>{value}</strong><span className={trend.startsWith('-') ? 'trend down' : 'trend'}>{trend}</span><small>{detail}</small></div> }
function Assignment({ name, person, progress, status, tone }: { name: string; person: string; progress: number; status: string; tone: string }) { return <div className="assignment-row"><div className={`person-dot ${tone}`}>{person.slice(0, 1)}</div><div className="assignment-info"><strong>{name}</strong><small>{person}</small></div><div className="assignment-progress"><div><span>{status}</span><b>{progress}%</b></div><div className="progress"><i style={{ width: `${progress}%` }} /></div></div><button className="row-arrow"><Icon name="arrow" size={15} /></button></div> }
function Deadline({ date, month, title, meta }: { date: string; month: string; title: string; meta: string }) { return <div className="deadline"><div className="date"><b>{date}</b><small>{month}</small></div><div><strong>{title}</strong><small>{meta}</small></div><Icon name="arrow" size={15} /></div> }
function Placeholder({ title, employee }: { title: string; employee: boolean }) {
  const [state, setState] = useState<'idle' | 'loading' | 'loaded' | 'error'>('idle')
  const endpoint = title === 'Assignments' ? (employee ? '/me/training-assignments' : '/training-assignments') : title === 'Qualifications' ? '/qualifications' : title === 'Certificates' ? (employee ? '/me/certificates' : '/certificates') : title === 'QR verification' ? (employee ? '/me/qr-code' : '/employees/me/qr-code') : title === 'Notifications' ? '/me/notifications' : title === 'Reports' ? '/reports/training-status' : title === 'Team insights' ? '/team/dashboard' : '/audit-logs'
  const icon = title === 'Assignments' ? 'book' : title === 'Qualifications' ? 'badge' : title === 'Certificates' ? 'certificate' : title === 'QR verification' ? 'qr' : title === 'Notifications' ? 'bell' : title === 'Reports' ? 'chart' : 'audit'
  async function load() { setState('loading'); try { await api(endpoint); setState('loaded') } catch { setState('error') } }
  return <div className="placeholder"><div className="placeholder-icon"><Icon name={icon as IconName} size={28} /></div><p className="eyebrow">NORTHSTAR WORKSPACE</p><h1>{title}</h1><p className="muted">{state === 'loaded' ? 'Live data loaded successfully.' : employee ? 'Your learning records and progress will appear here.' : 'This operational view is ready to connect to the API.'}</p><code className="endpoint">GET {apiBaseUrl}{endpoint}</code>{state === 'error' && <p className="error">Could not reach the API. Check your base URL and session.</p>}<button className="primary" onClick={load} disabled={state === 'loading'}>{state === 'loading' ? 'Loading...' : `Load ${title}`} {state !== 'loading' && <Icon name="arrow" size={16} />}</button></div>
}
